vscode:
  extensions:
    - DotJoshJohnson.xml
    - DotJoshJohnson.xml
    - vscjava.vscode-java-pack
    - redhat.java

tasks:
  - name: java project build with maven
    before: code --install-extension redhat.java
    init: mvn install -DskipTests=false
    command: |
      mvn compile
      # mvn exec:java -Dexec.mainClass="org.example.Main"
      mvn exec:java
