vscode:
  extensions:
    - DotJoshJohnson.xml
    - vscjava.vscode-java-pack
    - vscjava.vscode-java-debug
    - vscjava.vscode-java-dependency
    - vscjava.vscode-java-test
    - redhat.java
image:
  file: .gitpod.Dockerfile
tasks:
  - name: java project build with maven
    before: |
      code --install-extension redhat.java
      code --install-extension vscjava.vscode-java-pack
      code --install-extension DotJoshJohnson.xml
    init: |
      mvn install -DskipTests=false
    command: |
      mvn compile
      echo "Starting MySQL..."
      docker run --name mysql -e MYSQL_ROOT_PASSWORD=root -e MYSQL_DATABASE=testdb -p 3306:3306 -d mysql:latest

